export const HOLIDAY_PACKAGES = [
  {
    id: 'pkg-dubai-luxury',
    title: 'Dubai Luxury Escape',
    destination: 'Dubai, UAE',
    nights: 5, days: 6,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80&auto=format&fit=crop',
    price: 1299, oldPrice: 1899,
    rating: 4.8, reviews: 2340,
    tag: 'Best Seller',
    inclusions: ['Flights', 'Hotel 5★', 'Desert Safari', 'Burj Khalifa', 'Breakfast'],
    highlights: ['Burj Khalifa Tour', 'Dubai Mall Shopping', 'Desert Safari with BBQ'],
  },
  {
    id: 'pkg-bali-paradise',
    title: 'Bali Tropical Paradise',
    destination: 'Bali, Indonesia',
    nights: 6, days: 7,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80&auto=format&fit=crop',
    price: 899, oldPrice: 1299,
    rating: 4.9, reviews: 3120,
    tag: 'Trending',
    inclusions: ['Flights', 'Villa Stay', 'Ubud Tour', 'Spa', 'Daily Breakfast'],
    highlights: ['Ubud Monkey Forest', 'Tanah Lot Sunset', 'Private Villa Pool'],
  },
  {
    id: 'pkg-thailand-explorer',
    title: 'Thailand Beach & Culture',
    destination: 'Bangkok + Phuket',
    nights: 7, days: 8,
    image: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800&q=80&auto=format&fit=crop',
    price: 749, oldPrice: 1099,
    rating: 4.7, reviews: 1890,
    tag: 'Best Value',
    inclusions: ['Flights', '2 Cities', 'Island Tours', 'Tuk-tuk', 'Meals'],
    highlights: ['James Bond Island', 'Floating Market', 'Phi Phi Islands'],
  },
  {
    id: 'pkg-europe-classic',
    title: 'Europe Classic — 4 Countries',
    destination: 'Paris • Amsterdam • Brussels • Switzerland',
    nights: 9, days: 10,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
    price: 2499, oldPrice: 3299,
    rating: 4.9, reviews: 4210,
    tag: 'Premium',
    inclusions: ['Flights', '4 Countries', 'Train Pass', 'Hotels', 'City Tours'],
    highlights: ['Eiffel Tower Dinner', 'Amsterdam Canals', 'Jungfraujoch Glacier'],
  },
  {
    id: 'pkg-maldives-honeymoon',
    title: 'Maldives Honeymoon Special',
    destination: 'Maldives',
    nights: 4, days: 5,
    image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80&auto=format&fit=crop',
    price: 1799, oldPrice: 2499,
    rating: 5.0, reviews: 1560,
    tag: 'Romantic',
    inclusions: ['Flights', 'Water Villa', 'All Meals', 'Sunset Cruise', 'Spa'],
    highlights: ['Overwater Villa', 'Private Dinner', 'Snorkeling Tour'],
  },
  {
    id: 'pkg-singapore-family',
    title: 'Singapore Family Fun',
    destination: 'Singapore',
    nights: 4, days: 5,
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80&auto=format&fit=crop',
    price: 1149, oldPrice: 1599,
    rating: 4.8, reviews: 2780,
    tag: 'Family',
    inclusions: ['Flights', 'Hotel', 'Universal Studios', 'Sentosa', 'Sky Park'],
    highlights: ['Universal Studios', 'Gardens by the Bay', 'Marina Bay Sands'],
  },
  {
    id: 'pkg-japan-cherry',
    title: 'Japan Cherry Blossom Tour',
    destination: 'Tokyo • Kyoto • Osaka',
    nights: 7, days: 8,
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80&auto=format&fit=crop',
    price: 2199, oldPrice: 2899,
    rating: 4.9, reviews: 1890,
    tag: 'Seasonal',
    inclusions: ['Flights', 'Bullet Train', 'Hotels', 'Tea Ceremony', 'Mt. Fuji'],
    highlights: ['Cherry Blossom Parks', 'Mt. Fuji Day Trip', 'Geisha District'],
  },
  {
    id: 'pkg-usa-coast-coast',
    title: 'USA Coast to Coast',
    destination: 'New York • Las Vegas • LA',
    nights: 9, days: 10,
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80&auto=format&fit=crop',
    price: 2799, oldPrice: 3599,
    rating: 4.7, reviews: 1240,
    tag: 'Adventure',
    inclusions: ['Flights', '3 Cities', 'Grand Canyon Tour', 'Statue of Liberty', 'Hollywood'],
    highlights: ['Times Square', 'Grand Canyon Helicopter', 'Hollywood Walk'],
  },
];

export const HOLIDAY_CATEGORIES = [
  { id: 'all',       label: 'All Packages', emoji: '🌍' },
  { id: 'beach',     label: 'Beach & Islands', emoji: '🏝️' },
  { id: 'family',    label: 'Family',       emoji: '👨‍👩‍👧' },
  { id: 'honeymoon', label: 'Honeymoon',    emoji: '💕' },
  { id: 'adventure', label: 'Adventure',    emoji: '🏔️' },
  { id: 'luxury',    label: 'Luxury',       emoji: '✨' },
];