export const OFFERS = [
  {
    id:          'first-flight',
    title:       'First Flight Offer',
    discount:    '20% OFF',
    code:        'FIRSTFLY',
    description: 'New users get flat 20% off on their first booking',
    color:       'from-orange-500 to-pink-500',
    icon:        '✈️',
    expiresIn:   '7 days',
  },
  {
    id:          'international',
    title:       'International Special',
    discount:    '₹5,000 OFF',
    code:        'GOGLOBAL',
    description: 'Save big on international flights above ₹50,000',
    color:       'from-blue-500 to-purple-600',
    icon:        '🌍',
    expiresIn:   '15 days',
  },
  {
    id:          'domestic',
    title:       'Weekend Getaway',
    discount:    '15% OFF',
    code:        'WEEKEND15',
    description: 'Friday to Sunday domestic flights at lowest prices',
    color:       'from-green-500 to-teal-500',
    icon:        '🎒',
    expiresIn:   'Limited time',
  },
  {
    id:          'student',
    title:       'Student Discount',
    discount:    '12% OFF',
    code:        'STUDENT12',
    description: 'Special pricing for verified students',
    color:       'from-yellow-500 to-orange-500',
    icon:        '🎓',
    expiresIn:   'Always available',
  },
];