export const TESTIMONIALS = [
  {
    id:     1,
    name:   'Michael Anderson',
    role:   'Business Traveler',
    city:   'New York, USA',
    rating: 5,
    text:   "Booked my London business trip in under 2 minutes. When my meeting got rescheduled, their 24/7 support handled the change without any hassle. Truly best-in-class service.",
    avatar: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id:     2,
    name:   'Ahmed Al Mansouri',
    role:   'Frequent Flyer',
    city:   'Dubai, UAE',
    rating: 5,
    text:   "I've booked 20+ flights through ReservationKart for trips across Europe and Asia. The fares are unbeatable and the phone support is genuinely available whenever I need it.",
    avatar: 'https://i.pravatar.cc/150?img=33',
  },
  {
    id:     3,
    name:   'Sophie Laurent',
    role:   'Family Vacationer',
    city:   'Paris, France',
    rating: 5,
    text:   "Planned our entire family vacation to Bali — flights, hotels, all in one place. The interface is intuitive and the customer support actually feels human, not robotic.",
    avatar: 'https://i.pravatar.cc/150?img=47',
  },
  {
    id:     4,
    name:   'Priya Sharma',
    role:   'Solo Traveler',
    city:   'Mumbai, India',
    rating: 5,
    text:   "As a solo female traveler, I value security and reliability. ReservationKart delivers on both — transparent pricing, no hidden fees, and real human help whenever I need it.",
    avatar: 'https://i.pravatar.cc/150?img=44',
  },
];